AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - script/**
    - bin/**
    - tmp/**

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Description: "Limit lines to 120 characters."
  StyleGuide: "#120-character-limits"
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Style/ClassAndModuleChildren:
  EnforcedStyle: "compact"