version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current
file_exists_behavior: OVERWRITE

permissions: 
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 500
      runas: root
  