version: 0.2

run-as: root

env:
  secrets-manager:
    DOCKERHUB_PASS: "redes002@"
    DOCKERHUB_USERNAME: "lbneves"
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Build Container...
      - docker-compose build
      - echo Updating Gems...
      - docker-compose run --rm web bundle
      - echo Migrating Test Database...
      - docker-compose run --rm web rails db:create db:migrate RAILS_ENV=test
  build:
    commands:
      - echo Compile Assets...
      - docker-compose run --rm web rails assets:precompile