version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Build Container...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - docker-compose build
      - echo Updating Gems...
      - docker-compose run --rm web bundle
      - echo Migrating Test Database...
      - docker-compose run --rm web rails db:create db:migrate RAILS_ENV=test
  build:
    commands:
      - echo Nothing on build phase...

artifacts:
  files:
    - musclegrow-build.json