version: "3.3"
volumes:
  gems_musclegrow:

networks:
  net_musclegrow:
  
services:
  web: 
    build: .
    environment:
      MEMCACHED_SERVER: memcached:11211
    volumes:
      - gems_musclegrow:/usr/local/bundle
      - .:/app
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid; rails s -p 3000 -b '0.0.0.0'"
    networks: 
      - net_musclegrow
    depends_on:
      - db
      - memcached
  
  staging:
    build: .
    environment:
      RAILS_ENV: "staging"
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - gems_musclegrow:/usr/local/bundle
      - .:/app
    ports:
      - "80:3000"
    command: bash -c "rm -f tmp/pids/server.pid; rails s -p 3000 -b '0.0.0.0'"
    networks: 
      - net_musclegrow

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypass
    networks: 
      - net_musclegrow
    
  memcached:
    image: memcached:alpine
    networks: 
      - net_musclegrow