default: &default
  adapter: postgresql
  pool: 5
  host: db
  username: user
  password: mypass
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: musclegrow_development

test:
  <<: *default
  database: musclegrow_test

staging:
  <<: *default
  database: musclegrow_staging
  host: <%= Rails.application.credentials.dig(:staging, :db_host) %>
  username: <%= Rails.application.credentials.dig(:staging, :db_user) %>
  password: <%= Rails.application.credentials.dig(:staging, :db_password) %>
